import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/providers/ReduxProvider";
import TanstackProvider from "@/lib/tanstackQuery/TanstackProvider";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <TanstackProvider>
            {children}
            <Toaster
              richColors
              closeButton
              toastOptions={{
                className: "class",
              }}
              duration={3000}
            />
          </TanstackProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
